# Generated by Django 4.1.1 on 2022-10-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "price",
                    models.PositiveIntegerField(help_text="Positive Numbers only"),
                ),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=140)),
                (
                    "pet_friendly",
                    models.BooleanField(
                        default=False, help_text="Does this house allow pets?"
                    ),
                ),
            ],
        ),
    ]
