# Generated by Django 4.1.1 on 2022-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
